<h2>1 Dimensional Array</h2>

In [2]:
import numpy as np

<h2>1 Dimensional Array of Integers</h2>

In [3]:
arr1=np.array([x for x in range(1,11)])
print(arr1)
print(type(arr1))
print(f"dimensions of {arr1} is {arr1.shape}")
print(f"type of elements of {arr1} is {arr1.dtype}")

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
dimensions of [ 1  2  3  4  5  6  7  8  9 10] is (10,)
type of elements of [ 1  2  3  4  5  6  7  8  9 10] is int32


<h2>1 Dimensional Array of Strings</h2>

In [12]:
arr1=np.array(["Hello","World"])
print(arr1)
print(type(arr1))
'''
shape gives the row, column tuple (row,column)
ndim gives the dimension like 1D,2D,3D 
'''
print(f"dimensions of {arr1} is {arr1.shape}")
print(f"dimensions of {arr1} is {arr1.ndim}")
print(f"type of elements of {arr1} is {arr1.dtype}")

['Hello' 'World']
<class 'numpy.ndarray'>
dimensions of ['Hello' 'World'] is (2,)
dimensions of ['Hello' 'World'] is 1
type of elements of ['Hello' 'World'] is <U5


<h2>1 Dimensional Array of Integers and Strings</h2>

In [5]:
arr1=np.array(["Hello","World",1,2,3])
print(arr1)
print(type(arr1))
print(f"shape of {arr1} is {arr1.shape}")
print(f"type of elements of {arr1} is {arr1.dtype}")

['Hello' 'World' '1' '2' '3']
<class 'numpy.ndarray'>
dimensions of ['Hello' 'World' '1' '2' '3'] is (5,)
type of elements of ['Hello' 'World' '1' '2' '3'] is <U11


<h2>2 Dimensional Array</h2>

In [24]:
arr2=np.array([
                    [1,2,3],
                    [4,5,6],
                    [7,8,9]
             ])
print(f"{arr2}")
print(f"shape of arr2 are {arr2.shape}")
print(f"dimensions of arr2 are {arr2.ndim}")
print(f"number of elements of arr2 are {arr2.size}")
print(f"type of elements of arr2 are {arr2.dtype}")
# both lines bellow are equivalent
print(arr2[1,2])
print(arr2[1][2]) 


[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of arr2 are (3, 3)
dimensions of arr2 are 2
number of elements of arr2 are 9
type of elements of arr2 are int32
6
6


# 3D Arrays

In [20]:
x=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(x)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [28]:
a=[
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
    ]
# a is an array which contains two 2D arrays
# a  is a 3D array
y=np.array(a)
print(y[1])
print(y[0][0][0])
print(y[0,0,0])


[[ 7  8  9]
 [10 11 12]]
1
1


<h2>1 Dimensional Array with specific Data Type</h2>

In [8]:
arr2=np.array([1.2,3.3,5.904,6.5],np.float64)
print(f"{arr2}")
print(f"type of elements of arr2 are {arr2.dtype}")

[1.2   3.3   5.904 6.5  ]
type of elements of arr2 are float64


In [9]:
arr2=np.array([1.2,3,5.904,6.5],np.int64)
print(f"{arr2}")
print(f"type of elements of arr2 are {arr2.dtype}")

[1 3 5 6]
type of elements of arr2 are int64


<h2>Saving Array to a File</h2>

In [10]:
arr2=np.array([
                    [1,2,3],
                    [4,5,6],
                    [7,8,9]
             ])
# np.save("<file-name>",<name-of-array-variable>)
np.save("numpy_array",arr2)

<h2>Loading File from an array</h2>

In [11]:
loaded_array=np.load("numpy_array.npy")
print(f"{loaded_array}")
print(f"dimensions = {loaded_array.shape}")
print(f"Number of Elements = {loaded_array.size}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimensions = (3, 3)
Number of Elements = 9
