<h2>Array of Zeros</h2>

In [2]:
import numpy as np
x=np.zeros((3,3),np.int64)
print(f"{x}")
x=np.zeros((3,3))
print(f"{x}")

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<h2>Array of Ones</h2>

In [3]:
x=np.ones((2,3),np.int64)
print(x)        

[[1 1 1]
 [1 1 1]]


<h2>Array of Full of specific elements</h2>

In [4]:
# np.full(shape, constant value)
x=np.full((4,3),1)
print(x)


[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


<h2>Identity Martix</h2>

In [5]:
x=np.eye(5,dtype=np.int64)
print(x)
x=np.eye(3,dtype=np.int32)
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


<h2>Diagonal Matrix</h2>

In [6]:
x=np.diag([10,20])
print(x)
x=np.diag([10,20,30,40])
print(x)

[[10  0]
 [ 0 20]]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


<h2>arange function for producing integer array</h2>

In [7]:
# x=np.arange(start=0,stop,step=1)
x=np.arange(10)
print(x)
x=np.arange(1,10)
print(x)
x=np.arange(1,11,2)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


<h2>linespace function for producing float array</h2>

In [10]:
x=np.linspace(0.1,10.01)
print(x)

[ 0.1         0.3022449   0.5044898   0.70673469  0.90897959  1.11122449
  1.31346939  1.51571429  1.71795918  1.92020408  2.12244898  2.32469388
  2.52693878  2.72918367  2.93142857  3.13367347  3.33591837  3.53816327
  3.74040816  3.94265306  4.14489796  4.34714286  4.54938776  4.75163265
  4.95387755  5.15612245  5.35836735  5.56061224  5.76285714  5.96510204
  6.16734694  6.36959184  6.57183673  6.77408163  6.97632653  7.17857143
  7.38081633  7.58306122  7.78530612  7.98755102  8.18979592  8.39204082
  8.59428571  8.79653061  8.99877551  9.20102041  9.40326531  9.6055102
  9.8077551  10.01      ]


<h2>Creating Multidimensional Array using arange and reshape</h2>

In [ ]:
x=np.arange(1,10)
print(f"Orignal = {x}")
x=x.reshape(3,3)
print(x)
y=np.arange(1,10).reshape(3,3)
print(y)

Orignal = [1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


<h2>Array with random Numbers</h2>

In [ ]:
x=np.random.random()
print(x)
x=np.random.random((3,3))
print(x)
x=np.random.randint(1,10,size=(3,3))
print(x)

0.2059240109132886
[[0.19229565 0.20693956 0.14281604]
 [0.52593563 0.0253163  0.94258303]
 [0.75570061 0.74557899 0.49880196]]
[[5 8 8]
 [9 6 5]
 [3 5 4]]
