<h1>Array Slicing</h1>

In [3]:
import numpy as np

In [2]:
x=np.arange(20).reshape(4,5)
print(x)
# a=x[row_start:row_end-1,column_start:column_end-1] -1 is done by default
a=x[:2,:2]
print(a)
a=x[1:3,:]
print(a)
a=x[1:3,2:3]
print(a)
a=x[1:3,2:3]
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0 1]
 [5 6]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 7]
 [12]]
[[ 7]
 [12]]


<h1>Assigning sliced list to a variable and problem [Copy Function ]</h1>
array assignment follow shallow copy



In [3]:
x=np.arange(20).reshape(4,5)
print(x)
y=x[1:3,1:3]
print(y)
# changing the variable y also affects variable x
y[0,1]=-9
print(x)
print(y)
# in order to create an independant variable using list slicing use copy() function

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 6  7]
 [11 12]]
[[ 0  1  2  3  4]
 [ 5  6 -9  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 6 -9]
 [11 12]]


In [4]:
# Method 1 to use copy function of numpy
x=np.arange(20).reshape(4,5)
y=np.copy(x[2:3,:])
print(y)
y[0,2]=99
print(y)
print(x)


[[10 11 12 13 14]]
[[10 11 99 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [5]:
# Method 2 to use copy function of python lists
x=np.arange(20).reshape(4,5)
y=x[2:3,:].copy()
print(y)
y[0,2]=99
print(y)
print(x)


[[10 11 12 13 14]]
[[10 11 99 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


<h1>Diag Function</h1>

In [4]:
# 0 means main diagonal
# k<0 means bellow main diagonal
# k>0 means above main diagonal
x=np.arange(25).reshape(5,5)
print(x)
y=np.diag(x,0)
print("Elements of Main Diaognal are\n",y)
y=np.diag(x,1)
print("Elements Above Main Diaognal are\n",y)
y=np.diag(x,-1)
print("Elements Bellow Main Diaognal are\n",y)
# Unique Funcion to get unique values form an array
x=np.array([1,2,2,3,5,2,3])
print(np.unique(x))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Elements of Main Diaognal are
 [ 0  6 12 18 24]
Elements Above Main Diaognal are
 [ 1  7 13 19]
Elements Bellow Main Diaognal are
 [ 5 11 17 23]
[1 2 3 5]


KKK
