In [4]:
import numpy as np

<h1>Boolean Indexing</h1>

In [5]:
x=np.arange(1,26).reshape(5,5)
print(x)
y=x[(x>=10) & (x<=15)]
print("y=",y)
x[(x>=10) & (x<=15)]=0
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
y= [10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [ 0  0  0  0  0]
 [16 17 18 19 20]
 [21 22 23 24 25]]


<h1>Set Operations</h1>

In [4]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
print(np.setdiff1d(x,y)) # returns elements of "x" which are not in "y" (x-y)
print(np.intersect1d(x,y))
print(np.union1d(x,y))

[1 3 5]
[2 4]
[1 2 3 4 5 6 7 8]


<h1>Sorting Arrays</h1>

In [5]:
x=np.random.randint(1,20,10)
print(x)
# np.sort(<array-variable>) --> does not change the orignal array-variable
# <array-variable>.sort() --> changes the orignal array
print(np.sort(np.unique(x)))
print(x)

[16  6  1  4 11  7 19  5 18  5]
[ 1  4  5  6  7 11 16 18 19]
[16  6  1  4 11  7 19  5 18  5]


In [6]:
x=np.random.randint(1,20,10)
print(x)
x.sort()
print(x)
x=np.unique(x)
print(x)

[ 9 11 18  1 14  2 16  8  6 14]
[ 1  2  6  8  9 11 14 14 16 18]
[ 1  2  6  8  9 11 14 16 18]


# Sorting 2-D Arrays

In [7]:
# axis=0 ---> Sort by column
# axis=1 ---> Sort by row
x=np.random.randint(1,20,(4,4))
y=np.copy(x)
print(x)
print("Column wise Sort")
x.sort(axis=0)
print(x)
print("Row wise Sort")
y.sort(axis=1)
print(y)

[[14 17  9 17]
 [14 16  2  8]
 [ 4 18  1 18]
 [ 3  7  7  9]]
Column wise Sort
[[ 3  7  1  8]
 [ 4 16  2  9]
 [14 17  7 17]
 [14 18  9 18]]
Row wise Sort
[[ 9 14 17 17]
 [ 2  8 14 16]
 [ 1  4 18 18]
 [ 3  7  7  9]]
