# Array Arithmetic

In [1]:
import numpy as np          

# Arithmetic of 1-D Array

In [2]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(f"Addition\n {np.add(x,y)}")
print(f"Subtraction\n {np.subtract(x,y)}")
print(f"Multiplication\n {np.multiply(x,y)}")
print(f"Division\n {np.divide(x,y)}")

Addition
 [5 7 9]
Subtraction
 [-3 -3 -3]
Multiplication
 [ 4 10 18]
Division
 [0.25 0.4  0.5 ]


# Arithmetic of 2-D Array
same operations can also be performed using operators (+ - * /)

In [4]:
x=np.array([1,2,3,10]).reshape(2,2)
y=np.array([4,5,6,20]).reshape(2,2)
print(f"Addition\n {np.add(x,y)}")
print(f"Subtraction\n {np.subtract(x,y)}")
print(f"Multiplication\n {np.multiply(x,y)}")
print(f"Division\n {np.divide(x,y)}")
print("Power Function \n", np.power(x,3))
print("Square Root Function \n",np.sqrt(x))

Addition
 [[ 5  7]
 [ 9 30]]
Subtraction
 [[ -3  -3]
 [ -3 -10]]
Multiplication
 [[  4  10]
 [ 18 200]]
Division
 [[0.25 0.4 ]
 [0.5  0.5 ]]
Power Function 
 [[   1    8]
 [  27 1000]]
Square Root Function 
 [[1.         1.41421356]
 [1.73205081 3.16227766]]


# 